version: "3.8"

services:
  issue_tracker:
    build:
      context: ./issue_tracker
      args:
        - DEV=true
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./issue_tracker:/issue_tracker
    command: >
      sh -c "python manage.py makemigrations


