# Generated by Django 4.2.13 on 2024-05-22 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_label_issue_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='created_by',
        ),
    ]
