# Generated by Django 5.0.6 on 2024-07-01 06:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_issue_status"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="projectmembership",
            unique_together={("user", "project")},
        ),
    ]
