# .github/workflows/ci.yml
name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      ENVIRONMENT: test
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements.dev.txt
      working-directory: ./issue_tracker

    - name: Run linting
      run: |
        source venv/bin/activate
        flake8 .
      working-directory: ./issue_tracker

    - name: Run unit tests
      run: |
        source venv/bin/activate
        python manage.py test
      working-directory: ./issue_tracker
