---
name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  build-deploy-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Heroku Container Registry
      run: echo "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com

    - name: Build and Push Backend Docker image
      run: |
        docker buildx build --platform linux/amd64 -t registry.heroku.com/issue_tracker_backend/web -f ./issue_tracker/Dockerfile .
        docker push registry.heroku.com/issue_tracker_backend/web

    - name: Release Backend
      run: |
        heroku container:release web --app issue_tracker_backend

  build-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Heroku Container Registry
      run: echo "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com

    - name: Build and Push Frontend Docker image
      run: |
        docker buildx build --platform linux/amd64 -t registry.heroku.com/issue_tracker_frontend/web -f ./issue_tracker_frontend/Dockerfile .
        docker push registry.heroku.com/issue_tracker_frontend/web

    - name: Release Frontend
      run: |
        heroku container:release web --app issue_tracker_frontend
